"""empty message

Revision ID: 11f467cc423e
Revises: 9aafa74e3603
Create Date: 2020-11-14 11:01:52.076380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f467cc423e'
down_revision = '9aafa74e3603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('columns', sa.String(length=128), nullable=False))
    op.drop_column('config', 'fields')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('fields', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('config', 'columns')
    # ### end Alembic commands ###
